name: Mainnet Proposal

on:
  push:
    branches: [master]

env:
  SOLANA_CLI_VERSION: 1.8.5
  NODE_VERSION: 17.0.1

jobs:
  create-bonding-proposal:
    name: Create Bonding Proposal
    runs-on: ubuntu-18.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-with-gov-proposal/
        id: deploy
        with:
          program: spl_token_bonding
          program-id: TBondmkCYxaPCKG4CHYfVTcwQ8on31xnJrPzk8F8WsS
          network: https://api.mainnet-beta.solana.com
          keypair: ${{ secrets.DEPLOY_KEYPAIR }}
          governance: HDkW3MrrvqT9FPvuFBAVnSag1BLDx767MD2VXKfpCoCe
          name: Deploy ${{ github.ref_name }}
          description: https://github.com/StrataFoundation/strata/tree/${{ github.ref_name }}
      - uses: ./.github/actions/anchor-publish/
        with:
          program: spl_token_bonding
          anchor-token: ${{ secrets.ANCHOR_TOKEN }}

  create-collective-proposal:
    name: Create Collective Proposal
    runs-on: ubuntu-18.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-with-gov-proposal/
        id: deploy
        with:
          program: spl_token_collective
          program-id: TCo1sfSr2nCudbeJPykbif64rG9K1JNMGzrtzvPmp3y
          network: https://api.mainnet-beta.solana.com
          keypair: ${{ secrets.DEPLOY_KEYPAIR }}
          governance: 6yc2jb7LCjYXD3hbRKjYkpx13j4VXYcCBzYsZbmntdVk
          name: Deploy ${{ github.ref_name }}
          description: https://github.com/StrataFoundation/strata/tree/${{ github.ref_name }}
      - uses: ./.github/actions/anchor-publish/
        with:
          program: spl_token_collective
          anchor-token: ${{ secrets.ANCHOR_TOKEN }}
